/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "wgeskigohgnyuyfqocjg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnZXNraWdvaGdueXV5ZnFvY2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxMzAyODksImV4cCI6MjA4MTcwNjI4OX0.W-FDK3x-P7XR8ZlS0p0whXb_KvvxExppuoBzMTDfsC8"